### ISSUE TITLE
Buscar portales de transparencia u opendata

### ISSUE THREAD

**Issue by renatolrr** [renatolrr/Reto-OpenData-OpenDataDay2015#1]

**Comment by germaaan** [comment]
Andalucía: Universidad de Almería, Universidad de Cádiz, Universidad de Córdoba, Universidad de Huelva, Universidad de Jaén, Universidad de Málaga, Universidad Pablo de Olavide, Universidad de Sevilla

Aragón: Universida de Zaragoza

Canarias: Universidad las Palmas de G.C.

Cantabria: Universidad de Cantabria

Castilla y León: Universidad de Burgos, Universidad de Salamanca

Castilla-La Mancha:

Cataluña: Universitat de Barcelona, Universitat Pompeu Fabra

Comunidad de Madrid: Universidad de Alcalá, Universidad Rey Juan Carlos 

Comunidad Foral de Navarra:

Comunidad Valenciana: Universidad de Alicante

Extremadura:

Galicia: Universidad de Vigo

Islas Baleares: Universitat de les Illes Balears

La Rioja:

País Vasco:

Principado de Asturias:

Región de Murcia: Universidad de Murcia, Universidad de Politécnica de Cartagena

**Comment by renatolrr** [comment]
Nos centramos Andalucía:
Universidad Pablo de Olavide    https://datos.upo.gob.es/       http://www.upo.es/transparencia/  
Universidad de Cordoba  http://www.uco.es/transparencia/  
Universidad de Málaga  http://www.uma.es/cms/base/ver/section/document/7903/uma-transparente/  
Universidad de Cádiz   http://transparencia.uca.es/  
Universidad de Jaén    http://www10.ujaen.es/conocenos/organos-gobierno/ptransparencia  
Universidad de Almería http://cms.ual.es/UAL/transparencia/index.htm  
Universidad de Huelva   http://www.uhu.es/tr/  
Universidad de Granada  http://transparente.ugr.es      http://opendata.ugr.es

**Comment by juanAFernandez** [comment]
Esto no iría en el issue #2 ?

**Comment by germaaan** [comment]
Esto era más bien un propósito de intenciones, en #2 es dónde se va a seguir trabajando, sí. Cierro.
