### ISSUE TITLE
Análisis de los portales de transparencia de Andalucía

### ISSUE THREAD

**Issue by renatolrr** [renatolrr/Reto-OpenData-OpenDataDay2015#2]

**Comment by juanAFernandez** [comment]
**[Almería](http://cms.ual.es/UAL/transparencia/index.htm)**
El portal está bien. Según algunos [índices](http://cms.ual.es/UAL/universidad/serviciosgenerales/asuntoseconomicos/noticias/ssLINK/INFORMESGE) está entre los mejores puestos.
Sin embargo la memoria de los cursos donde están algunos datos académicos interesantes cambia de formato entre algunos años, esto debería mejorarse pero creo que nos podría servir.

**Comment by germaaan** [comment]
Vamos a especificar los datos básicos que vamos a usar en la comparativa de los portales de transparencia

**Comment by JJ** [comment]
¿Dónde lo especificáis?

**Comment by germaaan** [comment]
Estamos haciéndolo en una de las hojas del documento compartido https://docs.google.com/spreadsheets/d/1GOiHV3CAgWwD6h-eJwpfj04QRG0wRhZC0tquGFSQ1c0/edit#gid=1699420939

**Comment by germaaan** [comment]
Incluidos comentarios en presentación sobre cada portal de transparencia.
