### ISSUE TITLE
Buscar indicadores económicos 2006-2015

### ISSUE THREAD

**Issue by renatolrr** [renatolrr/Reto-OpenData-OpenDataDay2015#3]

**Comment by renatolrr** [comment]
Un posible indicador son los precios de la electricidad, procedo.

**Comment by renatolrr** [comment]
Indicadores de Actividad del Sector Servicios. Base 2005. CNAE-09, no dan un resultado significativo.

**Comment by renatolrr** [comment]
Una buena fuente buscada por Juan Antonio:
http://www.sepe.es/contenidos/que_es_el_sepe/estadisticas/otros_informes/sistesis_anual_MT.html

**Comment by JJ** [comment]
¿Habéis hecho algo con ella?

**Comment by juanAFernandez** [comment]
Como eran pocos datos se han extraído a mano. 
Sin embargo para ver el rendimiento de los estudiantes estamos analizando los premios nacionales que el ministerio ha convocado durante 6 años. El resultado pasado por tabula en csv es algo [así](https://raw.githubusercontent.com/renatolrr/Reto-OpenData-OpenDataDay2015/master/DatosUniversitarios/premios2006-2007.csv). Mi duda es si cuando tengamos los 6 ficheros hay que limpiarlos y pasarlos a alguna base de datos para hacer búsquedas o directamente a tablas. No se que sería más sencillo.
Al final la idea sería saber cuantos premios se han llevado estudiantes de cada ciudad y a lo mejor también en que titulaciones.

**Comment by JJ** [comment]
Esa tabla tenéis que limpiarla. Es más, yo creo que habría salido mejor transformando el PDF a txt y trabajando con él. Pero bueno, exportadlo (limpio) a CSV y a partir de ahí podéis hacer lo que queráis, incluso importarlo a una base de datos.

**Comment by juanAFernandez** [comment]
¿Por cierto Tabula no puede usarse desde linea de órdenes? Parece que sólo funciona con el portal web que te abre.

**Comment by juanAFernandez** [comment]
¿@jj cómo podríamos limpiar la tablas de forma eficiente? ¿Usando expresiones regulares? ¿Se podría hacer _"fácil"_ con Perl u otro lenguaje?

**Comment by germaaan** [comment]
Con expresiones regulares está haciendo el apaño ya.

**Comment by juanAFernandez** [comment]
sube el código que le echemos un ojo ;)

**Comment by germaaan** [comment]
Faltan 2009-2010 y 2010-2011 por limpiar que es lo que he comentado, al tener saltos de linea dentro de los campos y además otro texto a los lados es más difícil limpiarlos con el mismo procedimiento.

**Comment by JJ** [comment]
Por eso he dicho que igual habría sido más fácil usar pdf2txt o similar...
o pdftohtml... De todas formas comparte el script a ver si se pued emejorar.

**Comment by juanAFernandez** [comment]
En fusion tables, deberíamos unir en una misma gráfica demandantes y parados para ver relaciones.

**Comment by germaaan** [comment]
Ya están todos los archivos limpiados de datos universitarios. Había cosas que se tenían que arreglar a mano porque no había un patrón exacto.

**Comment by JJ** [comment]
Puedes poner "references #3" en el commit para que aparezca aquí el commit.
¿Qué queda, entonces?

**Comment by germaaan** [comment]
Estamos ya decidiendo como vamos a presentar los datos que hemos sacado, que son sobre diferentes aspectos, algunos relacionados entre sí.

**Comment by germaaan** [comment]
Indicadores económicos incluidos en la presentación, aunque no tantos como queríamos, además que no hemos podido hacer más comparaciones por falta de datos.
