### ISSUE TITLE
Comparación entre universidades: Salamanca - Granada / Córdoba - Granada

### ISSUE THREAD

**Issue by molocohb** [renatolrr/Reto-OpenData-OpenDataDay2015#5]
Comparación entre los datos de matrícula o demanda entre las universidades de Granada, Salamanca y Córdoba. 
Se escoge la comparación entre Granada - Salamanca por considerarse las ciudades universitarias de referencia para estudiantes a nivel nacional. 
Se escoge la compararación entre Granada - Córdoba por considerarse que la posible disminución de matrículas en ciudades universitarias de referencia puede suponer un aumento a favor de las matrículas en universidades locales. 
Links: 
Portal de Transparencia USAL http://diarium.usal.es/transparencia/ (datos de matrícula en http://campus.usal.es/~estadisticasgenerales/) OJO: el "portal" sólo es la portada, luego redirecciona a otras páginas. 
Portal de Transparencia UCO http://www.uco.es/transparencia/ (datos de matrícula en http://www.uco.es/transparencia/index.php/estudiantes/datos-de-estudiantes) 
Datos de matrículas en OpendataUGR, para tenerlos a mano: http://opendata.ugr.es/dataset?q=matr%C3%ADculas

**Comment by JJ** [comment]
¿Cómo vais a hacer esto? ¿Qué ficheros?

**Comment by molocohb** [comment]
Los que he puesto y los que estoy haciendo a partir de los que he puesto, ¿es correcto?

**Comment by germaaan** [comment]
Comparación general entre Almería, Cordoba y Granada y más especifica entre Cordoba y Granada incluidas en la presentación.
