### ISSUE TITLE
Preparar presentación

### ISSUE THREAD

**Issue by renatolrr** [renatolrr/Reto-OpenData-OpenDataDay2015#6]
Ya he subido algo al repo. Hay que completar, revisar y darle formato.

**Comment by juanAFernandez** [comment]
Podríamos hacer una rama gh-pages y usar reveal.js.
Aquí podéis ver un un [ejemplo](http://tikalk-cookbooks.github.io/chef_workshop_presentation/#/).

**Comment by renatolrr** [comment]
Mola, preparamos el realmente, y le damos forma.

**Comment by juanAFernandez** [comment]
Ya está reveal.js en la rama gh-pages. Sólo tienes que entrar en Setting y habilitar la página, eso sólo puede hacerlo tu. En cuanto lo hagas ya podremos acceder y ver como queda. Aunque también se puede ver de forma local.

**Comment by renatolrr** [comment]
Creo que ya está funcionando:
http://renatolrr.github.io/Reto-OpenData-OpenDataDay2015. 

Cierro, y ya me comentais
