### ISSUE TITLE
Puntos provisionales de la presentación

### ISSUE THREAD

**Issue by germaaan** [renatolrr/Reto-OpenData-OpenDataDay2015#8]
Introducción: historia y metodología de trabajo
Diversos portales de transparencia de universidades encontrados
Portales de transparencia de universidades andaluzas
Comparativa entre portales de transparencia
Datos económicos y evolución parados-demandantes en Andalucia
Comparativa evolución matriculaciones Granada-Cordoba
Premios Nacionales Excelencia Academica

**Comment by germaaan** [comment]
Punto importante: diferentes formatos de los datos que faciliten el procesamiento del mismo

**Comment by germaaan** [comment]
Relacionar datos económicos con número de matrículaciones no sé si está hecho por alguno

**Comment by juanAFernandez** [comment]
Los datos no son homogéneos en las matriculaciones. Hemos pensado en relacionar los datos de parados y demandantes con los de matriculaciones, pero no tenemos datos de toda Andalucía, sólo de UGR, UCO y UAL. Por eso hemos pensado que para poder hacer una comparativa mínima nos quedemos con esos 5 indicadores para poder sacar alguna conclusión.

**Comment by germaaan** [comment]
Pues esto ya está finalizado, muy buen trabajo a todos equipo!

**Comment by JJ** [comment]
¿Andestá la presentación?

El 23 de febrero de 2015, 14:28, German Martinez notifications@github.com
escribió:

> Pues esto ya está finalizado, muy buen trabajo a todos equipo!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/renatolrr/Reto-OpenData-OpenDataDay2015/issues/8#issuecomment-75540380
> .

## 

JJ

**Comment by germaaan** [comment]
Aquí anda andando: http://renatolrr.github.io/Reto-OpenData-OpenDataDay2015/#/
